version: '2'
services:
  ui:
    container_name: cfy_client
    build: ./Blood-inventory-frontEnd
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - api
  api:
    container_name: cfy_server
    build: ./Blood-inventory-Backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
